#!/bin/bash
set -e
id="3F9V_stndrd-cut_a"
printf 'pdb-id\tatoms\tresidues\tchains\n' > pdbinfo.txt

a=$(pdb_wc -a $id.pdb | awk "FNR == 1 { print \$3 }")
r=$(pdb_wc -r $id.pdb | awk "FNR == 1 { print \$3 }")
c=$(pdb_wc -c $id.pdb | awk "FNR == 1 { print \$3 }")
printf '%s\t%s\t%s\t%s\n' "$id" "$a" "$r" "$c" >> pdbinfo.txt

